/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconAdd: typeof import('./src/components/icons/IconAdd.vue')['default']
    IconClose: typeof import('./src/components/icons/IconClose.vue')['default']
    IconFile: typeof import('./src/components/icons/IconFile.vue')['default']
    IconMinus: typeof import('./src/components/icons/IconMinus.vue')['default']
    IconReload: typeof import('./src/components/icons/IconReload.vue')['default']
    IconSchedule: typeof import('./src/components/icons/IconSchedule.vue')['default']
    IconSuccess: typeof import('./src/components/icons/IconSuccess.vue')['default']
    IconUpload: typeof import('./src/components/icons/IconUpload.vue')['default']
    LoginBox: typeof import('./src/components/LoginBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
